name: Manual

# the workflow_call block was added to this manual workflow (on workflow_dispatch:) because
# it has to be included if a reuseable workflow is called.
# The changes from the workflow_dispatch inputs to the workflow_call inputs are:
# - "type: choice" is replaced with "type: string"
# - all "options:" are removed
# The variable/tag for the runner (var.RUNNER) is defined on the "Actions secrets and variables" page, tab "Variables":
# https://github.com/openfheorg/openfhe-development/settings/variables/actions
on:
  workflow_call:
    inputs:
      compiler:
        description: 'Compiler type'
        type: string
        required: true
        default: 'CLANG-18'
      openfhe_development_branch:
        description: 'openfhe-development branch/tag'
        type: string
        required: true
        default: 'main'
      openfhe_python_branch:
        description: 'openfhe_python branch/tag'
        type: string
        required: true
        default: 'main'
    
  workflow_dispatch:
    inputs:
      # Selects the compiler to use, this choice will be used in the COMPILERS_MAP as the key to
      # retrieve the corresponding cmake compiler options to pass to the action
      compiler:
        description: 'Compiler type'
        type: choice
        options:
        - 'GCC-14'
        - 'CLANG-18'
        required: true
        default: 'CLANG-18'
      openfhe_development_branch:
        description: 'openfhe-development branch/tag'
        type: string
        required: true
        default: 'main'
      openfhe_python_branch:
        description: 'openfhe_python branch/tag'
        type: string
        required: true
        default: 'main'

# As we are testing openfhe-numpy here, and not openfhe-development or openfhe_python, we do not need
# additional cmake options besides the compiler
jobs:
  call:
    uses: openfheorg/openfhe-numpy/.github/workflows/generic_workflow.yml@github-ci
    with:
      runner: ${{ vars.RUNNER }}
      compiler: "${{ inputs.compiler }}"
      openfhe_development_branch: "${{ inputs.openfhe_development_branch }}"
      openfhe_python_branch: "${{ inputs.openfhe_python_branch }}"
      

